[phases.setup]
nixPkgs = ["ffmpeg", "python3"]

[phases.install]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend",
  "pip install edge-tts"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "node backend/index.js"

[variables]
NODE_VERSION = "20.19.0"
