[phases.setup]
nixPkgs = ["ffmpeg", "python3"]

[phases.install]
cmds = [
    "npm install",
    "python3 -m venv /opt/venv",
    "/opt/venv/bin/pip install edge-tts"
]

[start]
cmd = "PATH=\"/opt/venv/bin:$PATH\" node index.js"

[variables]
NODE_VERSION = "20.19.0"
